default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  host: localhost
  database: ideasbox_development

test:
  <<: *default
  host: localhost
  database: ideasbox_tests

production:
  <<: *default
  database: ideasbox_production
  username: ideasbox
  password: <%= ENV['IDEASBOX_DATABASE_PASSWORD'] %>
