# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b709b927bf2e7052c2b4ff2ab15d624faa1868efb2e402ac178623ba88d7e16a3d1100efb7137cd5accd44c8b71102c14e44c5ea190e4ba9b5d15a0aa4e9940

test:
  secret_key_base: 6c0af1b2cae395336aa1445b515b3995afe7997364f4f321591d887ebc969578cfac367770189eaef0b1a8eeb94edcbae3c333c28431aae1200ad88743794762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
